# Generated by Django 5.2.3 on 2025-06-29 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0003_performancereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leaveid', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('PL', 'Privilege Leave'), ('CL', 'Casual Leave'), ('SL', 'Sick Leave'), ('LWP', 'Leave Without Pay')], max_length=4)),
                ('reason', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('delete_requested', 'Delete Requested')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveQuota',
            fields=[
                ('quotaid', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('PL', 'Privilege Leave'), ('CL', 'Casual Leave'), ('SL', 'Sick Leave'), ('LWP', 'Leave Without Pay')], max_length=4)),
                ('total_quota', models.FloatField()),
                ('used_quota', models.FloatField(default=0)),
                ('remain_quota', models.FloatField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('employee', 'leave_type')},
            },
        ),
    ]
